import 'package:flutter_enterprise_starter_kit/features/posts/domain/entities/post.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'post_model.freezed.dart';
part 'post_model.g.dart';

/// Data-layer DTO for JSONPlaceholder's `/posts` resource. Unlike `auth`'s
/// `User` (a plain mapper over an already-typed Firebase object), this is a
/// real JSON model: `fromJson`/`toJson` are generated by `json_serializable`
/// from the raw HTTP response body / cache entry.
@freezed
sealed class PostModel with _$PostModel {
  const factory PostModel({
    required int id,
    required int userId,
    required String title,
    required String body,
  }) = _PostModel;

  const PostModel._();

  factory PostModel.fromJson(Map<String, dynamic> json) =>
      _$PostModelFromJson(json);

  factory PostModel.fromDomain(Post post) => PostModel(
    id: post.id,
    userId: post.userId,
    title: post.title,
    body: post.body,
  );

  Post toDomain() => Post(id: id, userId: userId, title: title, body: body);
}
