// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2RdsqTKlxsOJ8ouKAGV9wgddCpw1WmZg',
    appId: '1:499329149829:web:6ff636f3aaf37cb5e9b2ec',
    messagingSenderId: '499329149829',
    projectId: 'flutter-enterprise-kit-dev',
    authDomain: 'flutter-enterprise-kit-dev.firebaseapp.com',
    storageBucket: 'flutter-enterprise-kit-dev.firebasestorage.app',
    measurementId: 'G-TYNB162W4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2K9tnNhXeKmBju7cKVbluUhkwOQZFLGQ',
    appId: '1:499329149829:android:521019fb9aaf2906e9b2ec',
    messagingSenderId: '499329149829',
    projectId: 'flutter-enterprise-kit-dev',
    storageBucket: 'flutter-enterprise-kit-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6772wXrISVI9YVYVHDI_Lu_Cjw-nGFCc',
    appId: '1:499329149829:ios:80a5a30264199c0ae9b2ec',
    messagingSenderId: '499329149829',
    projectId: 'flutter-enterprise-kit-dev',
    storageBucket: 'flutter-enterprise-kit-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterEnterpriseStarterKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6772wXrISVI9YVYVHDI_Lu_Cjw-nGFCc',
    appId: '1:499329149829:ios:80a5a30264199c0ae9b2ec',
    messagingSenderId: '499329149829',
    projectId: 'flutter-enterprise-kit-dev',
    storageBucket: 'flutter-enterprise-kit-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterEnterpriseStarterKit',
  );
}
