// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwyXHN971N7wNJKCExVQVOqsjtwDvDAig',
    appId: '1:257097491357:web:e21f6f8b144eb8a4914574',
    messagingSenderId: '257097491357',
    projectId: 'flutter-enterprise-kit-prod',
    authDomain: 'flutter-enterprise-kit-prod.firebaseapp.com',
    storageBucket: 'flutter-enterprise-kit-prod.firebasestorage.app',
    measurementId: 'G-E9Q6N5HTYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ8ZmxMvg2zprAmcn6ptmCr9oC9SgRZ1k',
    appId: '1:257097491357:android:51db5544ddcee072914574',
    messagingSenderId: '257097491357',
    projectId: 'flutter-enterprise-kit-prod',
    storageBucket: 'flutter-enterprise-kit-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7bNig9d4B_ZgSYT3HlJcS5EyFLVYCht0',
    appId: '1:257097491357:ios:2840fc1ea38c1f1c914574',
    messagingSenderId: '257097491357',
    projectId: 'flutter-enterprise-kit-prod',
    storageBucket: 'flutter-enterprise-kit-prod.firebasestorage.app',
    iosBundleId: 'com.example.flutterEnterpriseStarterKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7bNig9d4B_ZgSYT3HlJcS5EyFLVYCht0',
    appId: '1:257097491357:ios:2840fc1ea38c1f1c914574',
    messagingSenderId: '257097491357',
    projectId: 'flutter-enterprise-kit-prod',
    storageBucket: 'flutter-enterprise-kit-prod.firebasestorage.app',
    iosBundleId: 'com.example.flutterEnterpriseStarterKit',
  );
}
